services:
  - type: web
    name: hirevision-api
    runtime: python
    rootDir: Backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_BACKEND
        value: postgres
      - key: DATABASE_URL
        sync: false
      - key: CORS_ORIGINS
        sync: false
